### ISSUE TITLE
--pipe-location fails with absolute paths.

### ISSUE THREAD

**Issue by frcepeda** [omegaup/libinteractive#28]
If an absolute path is sent to `--pipe-location` (e.g. `/var/tmp`), the generated C code fails.

```
[ ERROR]  (libinteractive/run.c:125) mkdir : No such file or directory
[ ERROR]  (libinteractive/run.c:261) unlink /var/tmp/tesoro_in: No such file or directory
[ ERROR]  (libinteractive/run.c:261) unlink /var/tmp/tesoro_out: No such file or directory
```

The problem is that `recursively_mkdir_parent` fails when trying to create the first subdirectory, which it assumes cannot be empty.

**Comment by lhchavez** [comment]
welp, good catch.
